all:
  vars:
    ansible_user: "{{ lookup('env', 'LXC_USER') }}"
    ansible_password: "{{ lookup('env', 'LXC_PASSWORD') }}"
    ansible_become_password: "{{ lookup('env', 'LXC_PASSWORD') }}"

  children:
    proxmox_host:
      hosts:
        proxmox-pve:
          #ansible_host: 217.15.161.216 # Public IP of VPS Contabo
          ansible_connection: local # GitHub Runner on VPS Proxmox
          ansible_user: root
          ansible_password: "{{ PM_PASSWORD }}"
          ansible_become_password: "{{ PM_PASSWORD }}"
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    #rancher_server:
      #hosts:
        #rancher:
          #ansible_host: 192.168.2.111

    database_server:
      hosts:
        database:
          ansible_host: 192.168.2.110

    k3s_master:
      hosts:
        k3s-master:
          ansible_host: 192.168.2.120
          ansible_kubectl_executable: /usr/local/bin/k3s

    k3s_worker:
      hosts:
        k3s-worker:
          ansible_host: 192.168.2.121

    k3s_deploy:
      hosts:
        k3s-master:
          ansible_host: 192.168.2.120

    argocd_deploy:
      hosts:
        k3s-master:
          ansible_host: 192.168.2.120