apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount | default 2 }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: frontend
        image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
        imagePullPolicy: Always
        ports:
          - containerPort: {{ .Values.frontend.containerPort }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        livenessProbe:
          httpGet:
            #path: /health
            path: /
            port: {{ .Values.frontend.containerPort }}
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 3
        {{/*
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.frontend.containerPort }}
        */}}