apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
