---
- name: Create group prometheus
  group:
    name: prometheus
    state: present

- name: Create user prometheus (no login, no home)
  user:
    name: prometheus
    group: prometheus
    shell: /sbin/nologin
    create_home: no

- name: Create config/data folders
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  with_items:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download Prometheus binary
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp
    remote_src: yes

- name: Copy binary into /usr/local/bin
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: '0755'
    owner: prometheus
    group: prometheus
    remote_src: yes
  with_items:
    - prometheus
    - promtool

- name: Copy default config and web UI libraries
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: /etc/prometheus/
    owner: prometheus
    group: prometheus
    remote_src: yes
  with_items:
    - consoles
    - console_libraries
    - prometheus.yml

- name: Create systemd service file for Prometheus
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: Restart Prometheus

- name: Start & Enable Prometheus service
  systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes

- name: Config prometheus.yml file from template
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify: Reload Prometheus # Call handler to update config without restart service

- name: Download Node Exporter (used to collect data)
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp
    remote_src: yes

- name: Copy binary into /usr/local/bin
  ansible.builtin.copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: '0755'
    owner: root
    group: root
    remote_src: yes

- name: Create Systemd Service for Node Exporter
  ansible.builtin.copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      User=prometheus
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=multi-user.target

- name: Start Node Exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes